### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by Mengyu2019** [kwahid/C3_sarcopenia_data_descriptor#2]
Thanks for your reply sincerely. I‘m eager to get the resource of segemented skeletal muscle around C3 with tags for our automatic segemented models. I want to know whether SliceOmatic software can open the file (format: tag) directly? Do you have bought SliceOmatic software, which is expensive for me, a senior student, but is useful and more convenient to segement skeletal muscle compared with 3D slicer or Image J. I want to know whether it's deserved to buy it.
Last but no least, I'm a green hand for github, so it's difficult for me to run the code which is used for conversion from .tag to .dcm. Could you provide a more concrete README or steps to illustrate me to use the code and convert the format?
Thanks very much!
Best wishes!

**Comment by kwahid** [comment]
Hi there,

Thanks for your comment. I believe SliceOmatic is commercial software that needs to be purchased. The .tag format files are native to sliceOmatic. This is why we developed the NIfTI conversion code, so that we can convert these .tag files into a more universal format (i.e., NIfTI) that can be opened in 3D Slicer or Image J. 

Regarding the code, the notebook itself contains a small amount of documentation in comments and markdown format. You should be able to run it directly from a local environment (assuming you have access to the files). I'll see if I can add some documentation on the readme in the next few days to give more concrete steps in case it's useful. 

Thanks,

Kareem

**Comment by kwahid** [comment]
Added some brief documentation to the README. For what its worth, to run the entire code you will need access to the existing .tag files and DICOM files they were derived from. Please feel free to email me (kawahid@mdanderson.org) if you have any follow up questions.
